name: body_parser
authors:
  - Tobe O <thosakwe@gmail.com>
  - Ahmed Masoud
version: 1.1.1
description: Parse request bodies and query strings in Dart. Supports JSON,
  URL-encoded, and multi-part bodies.
homepage: https://github.com/angel-dart/body_parser
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  dart2_constant: ^1.0.2+dart2
  http_parser: ^4.0.0
  http_server: ^1.0.0
  mime: ^1.0.0

dev_dependencies:
  http: ^0.13.1
  test: ^1.16.8
  pedantic: ^1.11.0
